export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCEEDED = 'LOGIN_REQUEST_SUCCEEDED';
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED"
export const LOGOUT = 'LOGOUT';
export const LOGIN_REQUEST_RETRY = 'LOGIN_REQUEST_RETRY';
export const CHECK_EXPIRED_TIME = 'CHECK_EXPIRED_TIME';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_RESOURSE = 'GET_RESOURSE';





