export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCEEDED = 'LOGIN_REQUEST_SUCCEEDED';
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED"
export const LOGOUT = 'LOGOUT';



export const HANDLE_ERROR = 'HANDLE_ERROR';





