export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_RESOURSE = 'GET_RESOURSE';
//export const GET_COMMENTS = 'GET_COMMENTS';
export const RESOURSE_SUCCEEDED = 'RESOURSE_SUCCEDED';
export const RESOURSE_FAILED = 'RESOURSE_FAILED';
export const GET_TOKEN = 'GET_TOKEN';
export const CHECK_VALID_ACCESS_TOKEN = 'CHECK_VALID_ACCESS_TOKEN'
