
export const GET_TOKEN = 'GET_TOKEN';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';

//////REQUESTS
export const GET_COMMENTS = 'GET_COMMENTS';
export const COMMENTS_SUCCEEDED = 'COMMENTS_SUCCEDED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const GET_USERS = 'GET_USERS';
export const USERS_SUCCEEDED = 'USERS_SUCCEDED';
export const USERS_FAILED = 'USERS_FAILED';


