export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_RESOURSE = 'GET_RESOURSE';
export const CHECK_EXPIRED_TIME = 'CHECK_EXPIRED_TIME';
export const LOGIN_REQUEST_RETRY = 'LOGIN_REQUEST_RETRY';
export const CLEAN_VALIDATION_ERROR = 'CLEAN_VALIDATION_ERROR';





